
# default
spring:
  # 적용시킬 profile
  profiles:
    active: dev
  # multipart form-data 크기 지정
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 50MB

server:
  port: 80
  # Mock Mvc test response
  servlet:
    encoding:
      charset: UTF-8
      force: true

  # HTTP ssl 적용
#  ssl:
#    key-store: "classpath:{key}"
#    key-store-type: PKCS12
#    key-password:


---
# dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://localhost:3306/projectName?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
---
# prod
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: ${DATASOURCE}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false



